baseURL = "https://tver-it.ru"
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
languageCode = "ru-ru"
title = "Компьютерная помощь в Твери"
theme = "terminal"

[params]
  author = "Павел"
  description = "Настройка КриптоПро, ЭЦП, доступ к электронным прощадкам. Помощь удаленно через Ассистент в Твери."
  themeColor = "light" 
  prompt = "pasha@tver-it.ru:~$"

[params.logo]
  logoText = "Компьютерная помощь в Твери"
  logoHomeLink = "/"

[menu]
  # Стандартные разделы сайта
  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Блог"
    url = "/posts/"
    weight = 2

  # Кликабельный телефон (при нажатии со смартфона сразу пойдет вызов)
  [[menu.main]]
    identifier = "phone"
    name = " +7(903)802-45-20"
    url = "tel:+79038024520"
    weight = 3

  # Ссылка на твой Telegram
  [[menu.main]]
    identifier = "telegram"
    name = "Telegram"
    url = "https://t.me/Tver69it"
    weight = 4

  # Ссылка на твой Max Messenger
  [[menu.main]]
    identifier = "max"
    name = "Max"
    url = "https://max.ru/u/f9LHodD0cOLZ6l9NP0GNCbDsID6uvwUHyyakdDl7FBhclDgLHSrJsIWEeng"
    weight = 5
