baseURL = "https://tver-it.ru"
languageCode = "ru-ru"
title = "Компьютерная помощь в Твери"
theme = "terminal"

[params]
  author = "Павел"
  description = "Настройка КриптоПро, ЭЦП, доступ к электронным прощадкам. Помощь удаленно через Ассистент в Твери."
  
  # Цвета на выбор: "orange", "green", "blue", "pink", "red"
  themeColor = "green" 
  
  # Строка приглашения командной строки
  prompt = "pasha@tver-it.ru:~$"

[menu]
  # Переключатель страниц вверху терминала
  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1
  [[menu.main]]
    identifier = "posts"
    name = "Блог"
    url = "/posts/"
    weight = 2
