baseURL = "https://tver-it.ru/"
locale = "ru-ru"
title = "Компьютерная помощь в Твери | Настройка КриптоПро, ЭЦП и IT-поддержка"
theme = "congo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  description = "Компьютерная помощь в Твери. Настройка Windows, КриптоПро CSP, электронных подписей (ЭЦП), Госуслуг, ЕИС, электронных торговых площадок, удаленная IT-поддержка и выезд системного администратора."

  themeColor = "light"
  prompt = "pasha@tver-it.ru:~$"

  favicon = "/favicon.ico"

  keywords = [
    "компьютерная помощь Тверь",
    "системный администратор Тверь",
    "частный системный администратор Тверь",
    "настройка КриптоПро",
    "настройка ЭЦП",
    "КриптоПро Тверь",
    "электронная подпись",
    "ЕИС",
    "Госуслуги",
    "Честный Знак",
    "электронные торговые площадки",
    "настройка компьютеров",
    "удаленная компьютерная помощь"
  ]

[params.author]
  name = "Павел"

[params.header]
  logoText = "Компьютерная помощь в Твери"
  logoHomeLink = "/"

[menu]

  [[menu.main]]
    identifier = "home"
    name = "Главная"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Статьи"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "programs"
    name = "Программы"
    url = "/programs/"
    weight = 3

  [[menu.main]]
    identifier = "phone"
    name = "+7 (903) 802-45-20"
    url = "tel:+79038024520"
    weight = 4

  [[menu.main]]
    identifier = "telegram"
    name = "Telegram"
    url = "https://t.me/Tver69it"
    weight = 5

  [[menu.main]]
    identifier = "max"
    name = "MAX"
    url = "https://max.ru/u/f9LHodD0cOLZ6l9NP0GNCbDsID6uvwUHyyakdDl7FBhclDgLHSrJsIWEeng"
    weight = 6